imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$bq4sslCTNkXRIlstasjF2OSLREFunLtmYKj0FiE7/f0wE3AKPhodW
                        roles: 'ROLE_ADMIN'

    firewalls:
        main:
            logout:       true
            anonymous:    true
            http_basic: ~
